# Generated by Django 5.2.2 on 2025-06-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwerty', '0007_alter_customer_options_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='genre_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
